version: '3.8'

services:
  youtube-downloader:
    build: .
    container_name: yt-downloader
    ports:
      - "5001:5000"
    volumes:
      # Mount host directory for downloads - change this path as needed
      - ./downloads:/downloads
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    # Resource limits for Raspberry Pi
    mem_limit: 512m
    cpus: 1.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 60s  # Less frequent for Pi
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=http://raspberrypi.local:5001
    container_name: yt-downloader-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - youtube-downloader
    # Resource limits for Raspberry Pi
    mem_limit: 256m
    cpus: 0.5
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 60s  # Less frequent for Pi
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
