version: '3.8'

services:
  youtube-downloader:
    build: .
    container_name: yt-downloader
    ports:
      - "5001:5000"
    volumes:
      # Mount host directory for downloads - change this path as needed
      - ./downloads:/downloads
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
